apiVersion: v1
kind: Service
metadata:
  name: neon-runner-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: neon-runner-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
