apiVersion: v1
kind: Service
metadata:
  name: neon-runner-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: neon-runner-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}
