apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-runner-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: neon-runner-frontend
  template:
    metadata:
      labels:
        app: neon-runner-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
